abbr -a gs "git status"
abbr -a ga "git add"
abbr -a gc "git commit"
abbr -a gd "git diff"
abbr -a gl "git log"
abbr -a glols "git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset' --stat"
